### ISSUE TITLE
Crashing when trying to install on linux

### ISSUE THREAD

**Issue by Supamiu** [deadlinecode/dll-inject#10]
While this is a windows library, it could be included in a package.json that will be installed on linux for another usage (for my case: electron app that's built on windows but the web version is build on linux).

The issue is that node-gyp will obviously crash because it cannot build this on linux.

I believe the `"os"` top-level package.json property could help but I'm not sure it'd be enough, so I figured I should just report here 😄 

This is more of a feature request I guess, but a way to skip rebuild on non-win32 platform would be amazing.

**Comment by sdf010** [comment]
This is still an issue on void Linux, not with `npm install` but with `node-gyp rebuild` as called from the node package "@ffxiv-teamcraft/pcap-ffxiv" setting conditionals (as shown below) in `binding.gyp` seems to resolve this.

```
'conditions': [
   ['OS=="linux"', {'sources!': ['injector.cc','functions.cc']}]
 ],
```

**Comment by deadlinecode** [comment]
Im sadly not maintaining this package currently
However as soon as i have enough free time again im planing on making a new version of this package (under the same name new major version) that has a bit more options for injecting
