### ISSUE TITLE
Not building under electron 23.1.1

### ISSUE THREAD

**Issue by Supamiu** [deadlinecode/dll-inject#8]
So for some reason, this won't build in electron.

When installed, electron rebuilds native dependencies and this one one of them for my project.

I found no error log but found a config file that I can compare with the one produced by node-gyp:

https://www.diffchecker.com/oDtVwV8F/ (left is yours, right is electron).

I don't know if it's something that should be fixed in here tbh, but I'm asking just in case you already faced that issue 😄

**Comment by deadlinecode** [comment]
Yeah that seems odd
Mby a version mismatch between node-gyp and electron-gyp?
Anyways if you depend on it you can try to compile it yourself i think with https://www.electronjs.org/de/docs/latest/tutorial/using-native-node-modules#manually-building-for-electron

**Comment by deadlinecode** [comment]
Since i currently dont have that much time to work on this project it will take some time until i can start investigate in this

**Comment by Supamiu** [comment]
So it looks like it's building fine on electron 23.0.0 + Node 18.15.0

I guess this will be useful if anyone has the same issue and needs help at least :D
